version: '3'
services:
  cyton_service:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: cyton_simulation
    user: ros
    network_mode: host
    ipc: host
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID
    volumes:
      - ./docker/cyton_ros2:/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
      # - /dev/ttyUSB0:/dev/ttyUSB0
    stdin_open: true 
    tty: true
    command: ros2 launch cyton_ros2_gazebo cyton_simulation.launch.py