cyton_arm:

  #default:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver_search_resolution: 0.0050000000000000001
  # kinematics_solver_timeout: 0.0050000000000000001

  # works, fast, no ball to drag with mouse
    # kinematics_solver: ikfast_kinematics_plugin/IKFastKinematicsPlugin

# tańce wygibańce (po włączeniu cartesian path), jest kulka do szarpania myszką
  # kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin

# nie działa, ale to chyba dobrze
  # kinematics_solver: srv_kinematics_plugin/SrvKinematicsPlugin


    