

# PONIŻEJ ODKOMENTOWAĆ::::
controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_action_controller:
      type: position_controllers/GripperActionController

joint_trajectory_controller:
  ros__parameters:
    joints:
        - shoulder_roll_joint
        - shoulder_pitch_joint
        - elbow_roll_joint
        - elbow_pitch_joint
        - elbow_yaw_joint
        - wrist_pitch_joint
        - wrist_roll_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true

gripper_action_controller:
  ros__parameters:
    joint: gripper_joint

      