# Default initial positions for cyton's ros2_control fake system

initial_positions:
  elbow_pitch_joint: 0
  elbow_roll_joint: 0
  elbow_yaw_joint: 0
  gripper_joint: 0
  gripper_joint2: 0
  shoulder_pitch_joint: 0
  shoulder_roll_joint: 0
  wrist_pitch_joint: 0
  wrist_roll_joint: 0