# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - cyton_arm_controller
    # - cyton_hand_controller

  cyton_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
  # cyton_hand_controller:
  #   type: GripperCommand
  #   action_ns: gripper_cmd
  #   default: true
  #   joints:
  #     - gripper_joint
      # - mimic_gripper_joint