controller_list:
  - name: fake_manipulator_planning_group_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint7
      - joint6
  - name: fake_gripper_planning_group_controller
    joints:
      - joint8